export {default as LoginPage} from './LoginPage/LoginPage'
export {default as HomePage} from './HomePage/HomePage'
export {default as LocationPage} from './LocationPage/LocationPage'
export {default as MapPage} from './MapPage/MapPage'
//export {default as MapPage} from './MapPage/MapPage'
//export {default as DrugPage} from './DrugPage/DrugPage'